version: '3.7'

services:
  server:
    container_name: jobsgowhere-server
    ports:
      - '8080:8080'
    build: .
    environment:
      TZ: Asia/Singapore
      DATABASE_URL: postgres://jobsgowhere:randompasswordtobechangedinprod@db:5432/jobsgowhere?sslmode=disable
    depends_on:
      - db
  db:
    container_name: jobsgowhere-db
    ports:
      - '5432:5432'
    image: postgres:9.5-alpine
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: jobsgowhere
      POSTGRES_PASSWORD: randompasswordtobechangedinprod

